config/routes.rb
Spree::Core::Engine.add_routes do

  get '/dwolla/auth', :to => "dwolla#auth", :as => :dwolla_auth
  get '/dwolla/logout', :to => "dwolla#logout", :as => :dwolla_logout
  put '/dwolla', :to => "dwolla#pay", :as => :dwolla_pay
  get '/dwolla/return', :to => "dwolla#return", :as => :dwolla_return
  post '/dwolla/webhook/transaction_status', :to => "dwolla_webhook#transaction_status", :as => :dwolla_webhook

  post '/dwolla/update', :to => "dwolla#update", :as => :dwolla_update
  post '/dwolla/refund', :to => "dwolla#refund", :as => :dwolla_refund
end

app/views/spree/admin/payments/source_views/_dwolla.html.erb
<fieldset data-hook="dwolla">
  <legend align="center"><%= Spree.t(:transaction, :scope => :dwolla) %></legend>

  <div class="row">
    <div class="alpha six columns">
      <dl>
        <dt><%= Spree.t(:oauth_token, :scope => :dwolla) %>:</dt>
        <dd><%= payment.source.oauth_token %></dd>

        <dt><%= Spree.t(:transaction_id, :scope => :dwolla) %>:</dt>
        <dd><%= payment.source.transaction_id %></dd>
      </dl>
    </div>
  </div>

  <div class="row">
    <div class="alpha six columns">
      <p>Dwolla Actions:</p>

      <p>&bull; <%= link_to(Spree.t(:update, :scope => :dwolla), dwolla_update_url(:number => payment.order.number, :payment_id => payment.id), :method => :post) %></p>
    </div>
  </div>
</fieldset>

<% if payment.log_entries %>
<fieldset data-hook="dwolla">
  <legend><%= Spree.t(:payment_log, :scope => :dwolla) %></legend>

  <% payment.log_entries.reverse.each do |log| %>
  <div class="row dwolla_log_entry">
    <span>Updated at <%= log.updated_at %>:</span>
    <p><%= log[:details] %></p>
  </div>
  <% end %>
</fieldset>
<% end %>