config/routes.rb
Spree::Core::Engine.add_routes do

  get '/dwolla/auth', :to => "dwolla#auth", :as => :dwolla_auth
  get '/dwolla/logout', :to => "dwolla#logout", :as => :dwolla_logout
  put '/dwolla', :to => "dwolla#pay", :as => :dwolla_pay
  get '/dwolla/return', :to => "dwolla#return", :as => :dwolla_return
  post '/dwolla/webhook/transaction_status', :to => "dwolla_webhook#transaction_status", :as => :dwolla_webhook

  post '/dwolla/update', :to => "dwolla#update", :as => :dwolla_update
  post '/dwolla/refund', :to => "dwolla#refund", :as => :dwolla_refund
end

app/views/spree/checkout/payment/_dwolla.html.erb
<div class="connect_dwolla">
  <% if not session[:dwolla_oauth_token] %>
  <p><%= Spree.t(:oauth_text, :scope => :dwolla) %></p>

  <div class="button_wrapper">
    <%= link_to('Connect with Dwolla', dwolla_auth_url, :id => "dwolla_button") %>
  </div>
  <% else %>
  <p><%= (Spree.t(:oauth_logout, :scope => :dwolla) % [session[:dwolla_name], dwolla_logout_url]).html_safe %></p>

  <fieldset class="no-border-bottom">
    <% if session[:dwolla_funding_sources] %>
    <div class="row">
      <div data-hook="dwolla_funding_source">
        <div class="field">
          <%= label_tag 'dwolla_funding_source', raw(Spree.t(:dwolla_funding_source, :scope => :dwolla) + content_tag(:span, ' *', :class => 'required')) %>
          <%= select_tag :dwolla_funding_source, options_for_select(session[:dwolla_funding_sources]) %>
        </div>
      </div>
    </div>
    <% end %>

    <div class="row">
      <div data-hook="dwolla_pin">
        <div class="field">
          <%= label_tag 'dwolla_pin', raw(Spree.t(:dwolla_pin, :scope => :dwolla) + content_tag(:span, ' *', :class => 'required')) %>
          <%= password_field_tag :dwolla_pin, '', :class => 'required fullwidth', :maxlength => 4 %>
        </div>
      </div>
    </div>
  </fieldset>
  <% end %>
</div>

<script>
  SpreeDwolla.paymentMethodID = "<%= payment_method.id %>"
  SpreeDwolla.dwollaId = "<%= session[:dwolla_id] %>"
</script>

app/views/spree/checkout/payment/dwolla_cancel.html.erb
<html>
  <head>
    <script type="text/javascript">
      setTimeout(function() {
        window.close();
      }, 100);
    </script>
  </head>
  <body>
    <p>Please wait. Closing window now...</p>
  </body>
</html>

app/views/spree/checkout/payment/dwolla_return.html.erb
<html>
  <head>
    <script type="text/javascript">
      setTimeout(function() {
        window.opener.location = '<%= url %>';
        window.close();
      }, 100);
    </script>
  </head>
  <body>
    <p>Please wait. Redirecting you back now...</p>
  </body>
</html>